development:
  dialect: postgres
  database: piia
  user: homestead
  password: secret
  host: 127.0.0.1
  port: 54320
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/piia_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/piia_production?sslmode=disable"}}
