development:
  dialect: postgres
  database: {{ envOr "DATABASE_NAME" "postgres" }}
  user: {{ envOr "DATABASE_USER" "postgres" }}
  password: {{ envOr "DATABASE_PASSWORD" "postgres" }}
  host: {{ envOr "DATABASE_HOST" "localhost" }}
  port: {{ envOr "DATABASE_PORT" "5432" }}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/piia_test?sslmode=disable"}}

production:
  # url: {{envOr "DATABASE_URL" "postgres://piia:piia@127.0.0.1:5432/piiadb?sslmode=disable"}}
  dialect: postgres
  database: {{ env "DATABASE_NAME" }}
  user: {{ env "DATABASE_USER" }}
  password: {{ env "DATABASE_PASSWORD" }}
  host: {{ env "DATABASE_HOST" }}
  port: {{ env "DATABASE_PORT" }}
  pool: 5
